"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@material-tailwind/react";
import Navbarr from "./Component/Navbarr";
import { useEffect, useState } from "react";
import Footer from "./Component/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [domLoaded, setDomLoaded] = useState(false);

  useEffect(() => {
    setDomLoaded(true);
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        {domLoaded && (
          <ThemeProvider>
            <Navbarr />
            {children}
            <Footer/>
          </ThemeProvider>
        )}
      </body>
    </html>
  );
}
